"""make junction table names more explicit

Revision ID: 2d2b5f5212ac
Revises: 3e4e42c7846c
Create Date: 2018-08-03 20:04:32.846426

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "2d2b5f5212ac"
down_revision = "3e4e42c7846c"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "sensor_category_junction",
        sa.Column("sensor_id", sa.Integer(), nullable=False),
        sa.Column("category_id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(["category_id"], ["category.id"]),
        sa.ForeignKeyConstraint(["sensor_id"], ["sensor.id"]),
        sa.PrimaryKeyConstraint("sensor_id", "category_id"),
    )
    op.create_table(
        "user_sensor_junction",
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("sensor_id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(["sensor_id"], ["sensor.id"]),
        sa.ForeignKeyConstraint(["user_id"], ["user.id"]),
        sa.PrimaryKeyConstraint("user_id", "sensor_id"),
    )
    op.drop_table("categories")
    op.drop_table("sensors")
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "sensors",
        sa.Column("user_id", sa.INTEGER(), nullable=False),
        sa.Column("sensor_id", sa.INTEGER(), nullable=False),
        sa.ForeignKeyConstraint(["sensor_id"], ["sensor.id"]),
        sa.ForeignKeyConstraint(["user_id"], ["user.id"]),
        sa.PrimaryKeyConstraint("user_id", "sensor_id"),
    )
    op.create_table(
        "categories",
        sa.Column("sensor_id", sa.INTEGER(), nullable=False),
        sa.Column("category_id", sa.INTEGER(), nullable=False),
        sa.ForeignKeyConstraint(["category_id"], ["category.id"]),
        sa.ForeignKeyConstraint(["sensor_id"], ["sensor.id"]),
        sa.PrimaryKeyConstraint("sensor_id", "category_id"),
    )
    op.drop_table("user_sensor_junction")
    op.drop_table("sensor_category_junction")
    # ### end Alembic commands ###
