"""last_updated field for Sensor model

Revision ID: 4e5ac6ea1400
Revises: c0bb6d55b675
Create Date: 2018-07-18 20:17:08.310572

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "4e5ac6ea1400"
down_revision = "c0bb6d55b675"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("sensor", sa.Column("last_updated", sa.DateTime(), nullable=True))
    op.create_index(
        op.f("ix_sensor_last_updated"), "sensor", ["last_updated"], unique=False
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_sensor_last_updated"), table_name="sensor")
    op.drop_column("sensor", "last_updated")
    # ### end Alembic commands ###
