"""add password_hash column to User

Revision ID: 750c629371d0
Revises: 2d2b5f5212ac
Create Date: 2018-08-11 21:02:35.129986

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "750c629371d0"
down_revision = "2d2b5f5212ac"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "user", sa.Column("password_hash", sa.String(length=128), nullable=True)
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("user", "password_hash")
    # ### end Alembic commands ###
