"""add user token

Revision ID: 9a1cc19123a5
Revises: 750c629371d0
Create Date: 2018-08-13 19:30:22.353151

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "9a1cc19123a5"
down_revision = "750c629371d0"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("user", sa.Column("token", sa.String(length=32), nullable=True))
    op.add_column("user", sa.Column("token_expiration", sa.DateTime(), nullable=True))
    op.create_index(op.f("ix_user_token"), "user", ["token"], unique=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_user_token"), table_name="user")
    op.drop_column("user", "token_expiration")
    op.drop_column("user", "token")
    # ### end Alembic commands ###
