"""many-to-many w/ sensor and categories

Revision ID: c0bb6d55b675
Revises: 80de45bdcf9e
Create Date: 2018-07-14 23:31:49.823666

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "c0bb6d55b675"
down_revision = "80de45bdcf9e"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "categories",
        sa.Column("sensor_id", sa.Integer(), nullable=False),
        sa.Column("category_id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(["category_id"], ["category.id"]),
        sa.ForeignKeyConstraint(["sensor_id"], ["sensor.id"]),
        sa.PrimaryKeyConstraint("sensor_id", "category_id"),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("categories")
    # ### end Alembic commands ###
